### ISSUE TITLE
peepdf Errors

### ISSUE THREAD

**Issue by kevthehermit** [viper-framework/viper#120]
Peepdf generates errors that are written in to an errors.txt file in the root of viper. It looks like an issue with relative imports. 

Example show here

```
Traceback (most recent call last):
  File "/home/thehermit/GitHub/viper/modules/peepdf/JSAnalysis.py", line 75, in analyseJS
    code = jsbeautifier.beautify(code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 93, in beautify
    return b.beautify(string, opts)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 210, in beautify
    self.input = self.unpack(s, opts.eval_code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 245, in unpack
    import jsbeautifier.unpackers as unpackers
ImportError: No module named jsbeautifier.unpackers
Traceback (most recent call last):
  File "/home/thehermit/GitHub/viper/modules/peepdf/JSAnalysis.py", line 75, in analyseJS
    code = jsbeautifier.beautify(code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 93, in beautify
    return b.beautify(string, opts)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 210, in beautify
    self.input = self.unpack(s, opts.eval_code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 245, in unpack
    import jsbeautifier.unpackers as unpackers
ImportError: No module named jsbeautifier.unpackers
Traceback (most recent call last):
  File "/home/thehermit/GitHub/viper/modules/peepdf/JSAnalysis.py", line 75, in analyseJS
    code = jsbeautifier.beautify(code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 93, in beautify
    return b.beautify(string, opts)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 210, in beautify
    self.input = self.unpack(s, opts.eval_code)
  File "/home/thehermit/GitHub/viper/modules/peepdf/jsbeautifier/__init__.py", line 245, in unpack
    import jsbeautifier.unpackers as unpackers
ImportError: No module named jsbeautifier.unpackers
```

**Comment by enikhu** [comment]
Seperatr STIx config from TAXII

**Comment by botherder** [comment]
Can we revive this ticket and look into whether there's been progress in latest versions of peepdf?

**Comment by Rafiot** [comment]
peepdf is huge (16K lines of code) and not python3 compatible. Right now, we only use it to extract streams, which is something pdf-parser can do (see python 3 PR).

**Comment by SYNchroACK** [comment]
@Rafiot I think now is possible. I did:
```
apt-get install libjpeg8-dev
pip3 install Pillow
pip3 install peepdf
```

**Comment by Rafiot** [comment]
and does it work? Because I've seen *lots* of libraries that are installable with python3, but almost titally broken.
