### ISSUE TITLE
pip install -r requirements.txt met error

### ISSUE THREAD

**Issue by jiamo** [viper-framework/viper#303]
Installing collected packages: OleFileIO-PL, oletools, bottle, pylzma, pyelftools, bitstring, dnspython, pyexiftool
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 299, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 813, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1008, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 341, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: OleFileIO-PL .dist-info directory not found

**Comment by botherder** [comment]
As I understand, OleFileIO is deprecated and is replaced by olefile. We should remove it entirely but it seems that the module `emailparse` is still using OleFileIO. @kevthehermit could you take care of that?

**Comment by kevthehermit** [comment]
https://github.com/viper-framework/viper/pull/304

**Comment by kevthehermit** [comment]
Fixed
