### ISSUE TITLE
PST module needs better error handling

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#321]
PST module isn't handling errors and unexpected conditions well. For example, it doesn't check whether a session is open or not.

```
[!] The command pst raised an exception:
Traceback (most recent call last):
  File "/home/nex/viper/git/viper/core/ui/console.py", line 259, in start
    module.run()
  File "/home/nex/viper/git/modules/pst.py", line 102, in run
    pst_path = __sessions__.current.file.path
AttributeError: 'NoneType' object has no attribute 'file'
```

**Comment by kevthehermit** [comment]
On it

**Comment by Rafiot** [comment]
Fixed by https://github.com/viper-framework/viper/pull/495/commits/deae74f827b0a0c7252ba59e74ab9738dbf71cd0
