### ISSUE TITLE
ImportError: No module named prettytable

### ISSUE THREAD

**Issue by umbre42** [viper-framework/viper#343]
Hi all,

Not being a Python dude, I tried anyway to launch Viper.

After doing what is said in the documentation, I get:

~/viper-1.2$ ./viper.py 
Traceback (most recent call last):
  File "./viper.py", line 7, in <module>
    from viper.core.ui import console
  File "/home/umb/viper-1.2/viper/core/ui/console.py", line 10, in <module>
    from viper.common.out import *
  File "/home/umb/viper-1.2/viper/common/out.py", line 4, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable

I have installed python-prettytable by the way.

Thank you !

**Comment by umbre42** [comment]
Forget it I had a virtualenv running from another tool I had just compiled. Sorry for the disturbance.
