### ISSUE TITLE
Bug in Adzok module

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#366]
```Traceback (most recent call last):
  File "/home/nex/projects/viper/git/viper/core/ui/console.py", line 270, in start
    module.run()
  File "/home/nex/projects/viper/git/modules/rat.py", line 97, in run
    self.get_config(self.args.family)
  File "/home/nex/projects/viper/git/modules/rat.py", line 56, in get_config
    config = module.config(__sessions__.current.file.data)
  File "/home/nex/projects/viper/git/modules/rats/adzok.py", line 26, in config
    with ZipFile(file_name, 'r') as zip:
NameError: global name 'file_name' is not defined```

**Comment by kevthehermit** [comment]
fixed with https://github.com/viper-framework/viper/commit/22d234c4ef65e2cfe93bf9426796703a552e18fa
