### ISSUE TITLE
viper-update can't properly fetch and write the master zip archive

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#420]
When trying to issue a `viper-update --core` command, it currently fails:

```
[!] WARNING: If you proceed you will lose any changes you might have made to Viper.
Are you sure you want to proceed? [y/N] y
Traceback (most recent call last):
  File "/usr/local/bin/viper-update", line 4, in <module>
    __import__('pkg_resources').run_script('viper==1.3', 'viper-update')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1670, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3-py2.7.egg/EGG-INFO/scripts/viper-update", line 204, in <module>
    update()
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3-py2.7.egg/EGG-INFO/scripts/viper-update", line 52, in update
    zip_data.write(unicode(master))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 10: ordinal not in range(128)
```

**Comment by botherder** [comment]
Can't reproduce anymore.
