### ISSUE TITLE
viper-update currently broken, expected unicode gets str

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#444]
```
Traceback (most recent call last):
  File "/usr/local/bin/viper-update", line 4, in <module>
    __import__('pkg_resources').run_script('viper==1.3', 'viper-update')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3-py2.7.egg/EGG-INFO/scripts/viper-update", line 213, in <module>
    update()
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3-py2.7.egg/EGG-INFO/scripts/viper-update", line 52, in update
    zip_data.write(master)
TypeError: unicode argument expected, got 'str'
```

**Comment by Beercow** [comment]
Changing StringIO to BytesIO fixes the issue.

**Comment by botherder** [comment]
It did, thanks.

**Comment by Beercow** [comment]
There is also an indent issue with line 116 and 117.
