### ISSUE TITLE
ImportError at launch

### ISSUE THREAD

**Issue by Tux-Panik** [viper-framework/viper#520]
Hello,

Currently trying to use last viper release on remnux VM.
Used commands to prepare installation:

`sudo apt-get install gcc python-dev python3-pip`
`sudo apt-get install libssl-dev swig`
`sudo pip3 install SQLAlchemy PrettyTable python-magic`
`sudo pip3 install -r requirements.txt`

Then, moving on installation folder:
`user@host:/opt/remnux-viper$ ls -l`
>total 128
drwxr-xr-x  9 root root           4096 Apr 11 09:37 ./
drwxr-xr-x 34 root root           4096 Feb 27 10:13 ../
drwxr-xr-x  7 root root           4096 Apr 11 09:28 build/
-rw-r--r--  1 gift sansforensics  3211 Apr 11 09:04 CHANGELOG
-rw-r--r--  1 gift sansforensics   720 Apr 11 09:04 CONTRIBUTING.md
drwx------  5 gift sansforensics  4096 Apr 11 09:04 data/
drwxr-xr-x  2 root root           4096 Apr 11 09:28 dist/
drwx------  3 gift sansforensics  4096 Apr 11 09:04 docs/
-rw-r--r--  1 gift sansforensics  1701 Apr 11 09:04 LICENSE
-rw-r--r--  1 gift sansforensics   436 Apr 11 09:04 Makefile
-rw-r--r--  1 gift sansforensics  1515 Apr 11 09:04 README.md
-rw-r--r--  1 gift sansforensics   767 Apr 11 09:04 requirements.txt
-rw-r--r--  1 gift sansforensics   441 Apr 11 09:04 setup.py
drwx------  6 gift sansforensics  4096 Apr 11 09:28 viper/
-rwxr-xr-x  1 gift sansforensics 13430 Apr 11 09:04 viper-api*
-rwxr-xr-x  1 gift sansforensics   659 Apr 11 09:04 viper-cli*
-rw-r--r--  1 gift sansforensics  2052 Apr 11 09:14 viper.conf
-rw-r--r--  1 root root           2030 Apr 11 09:29 viper.conf.sample
drwxr-xr-x  2 root root           4096 Apr 11 09:11 viper.egg-info/
-rwxr-xr-x  1 gift sansforensics  8127 Apr 11 09:04 viper-update*
-rwxr-xr-x  1 gift sansforensics 28529 Apr 11 09:04 viper-web*

`user@host:/opt/remnux-viper$ python3 viper-cli`
>Traceback (most recent call last):
  File "viper-cli", line 7, in <module>
    from viper.core.ui import console
ImportError: No module named 'viper.core.ui'

`user@host:/opt/remnux-viper$ python2 viper-cli`
>Traceback (most recent call last):
  File "viper-cli", line 7, in <module>
    from viper.core.ui import console
ImportError: No module named core.ui

Note that `sudo make install` didn't change anything.

**Did I missed something?**
Thanks in advance for your help.
Regards,

**Comment by Tux-Panik** [comment]
Humm, it was a rights issue...
Sorry for inconvenience :-/
