### ISSUE TITLE
AttributeError: Config instance has no attribute 'logging'

### ISSUE THREAD

**Issue by corq** [viper-framework/viper#543]
All dependencies appear to build fine, then running viper-web results in issues:

./viper-web 
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:18: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:36: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
Traceback (most recent call last):
  File "./viper-web", line 31, in <module>
    from viper.core.session import __sessions__
  File "/opt/viper/viper/core/session.py", line 9, in <module>
    from viper.core.database import Database
  File "/opt/viper/viper/core/database.py", line 21, in <module>
    from viper.core.project import __project__
  File "/opt/viper/viper/core/project.py", line 61, in <module>
    __project__ = Project()
  File "/opt/viper/viper/core/project.py", line 30, in __init__
    if cfg.logging.log_file:
AttributeError: Config instance has no attribute 'logging'

Same with viper-cli:

./viper-cli
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:18: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/mispevent.py:45: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
/usr/local/lib/python2.7/dist-packages/pymisp/api.py:36: UserWarning: You're using python 2, it is strongly recommended to use python >=3.4
  warnings.warn("You're using python 2, it is strongly recommended to use python >=3.4")
Traceback (most recent call last):
  File "./viper-cli", line 7, in <module>
    from viper.core.ui import console
  File "/opt/viper/viper/core/ui/console.py", line 16, in <module>
    from viper.core.session import __sessions__
  File "/opt/viper/viper/core/session.py", line 9, in <module>
    from viper.core.database import Database
  File "/opt/viper/viper/core/database.py", line 21, in <module>
    from viper.core.project import __project__
  File "/opt/viper/viper/core/project.py", line 61, in <module>
    __project__ = Project()
  File "/opt/viper/viper/core/project.py", line 30, in __init__
    if cfg.logging.log_file:
AttributeError: Config instance has no attribute 'logging'

################# invoking python3 gets me:

python3 viper-cli
Traceback (most recent call last):
  File "viper-cli", line 7, in <module>
    from viper.core.ui import console
  File "/opt/viper/viper/core/ui/console.py", line 16, in <module>
    from viper.core.session import __sessions__
  File "/opt/viper/viper/core/session.py", line 9, in <module>
    from viper.core.database import Database
  File "/opt/viper/viper/core/database.py", line 11, in <module>
    from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text
ImportError: No module named 'sqlalchemy'

 python3 viper-web
  File "viper-web", line 408
    print new_file
                 ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by gra55h0pp3r** [comment]
I've got the same issue now as well. I just did a git pull to get the updated changes and that's when my VIPER broke. ;-(

**Comment by Rafiot** [comment]
sorry for that, it is patched in the py3 branch (https://github.com/viper-framework/viper/pull/495), we're merging it tomorrow.

**Comment by corq** [comment]
Grazi!
