### ISSUE TITLE
Module email not working on Python3 with .msg

### ISSUE THREAD

**Issue by frennkie** [viper-framework/viper#566]
I ran into an issue with an Outlook Mail (.msg) that is working on Py2 but not on Py3:

```
misc viper mail.msg > email -a
[*] Email envelope:
+---------+-------+
| Key     | Value |
+---------+-------+
| Subject | None  |
| To      | None  |
| From    | None  |
| Cc      | None  |
| Bcc     | None  |
| Date    | None  |
+---------+-------+
[!] The command email raised an exception:
Traceback (most recent call last):
  File "/home/viper/viper_prod/viper/viper/core/ui/console.py", line 258, in start
    module.run()
  File "/home/viper/viper_prod/viper/viper/modules/emailparse.py", line 482, in run
    email_header(msg)
  File "/home/viper/viper_prod/viper/viper/modules/emailparse.py", line 192, in email_header
    for x in msg.get_all('Received'):
TypeError: 'NoneType' object is not iterable
misc viper mail.msg >
```

I'll try to find some time to look into it.

**Comment by frennkie** [comment]
parse_ole_msg stumples over:

```
Traceback (most recent call last):
  File "/home/viper/viper_testing/viper/viper/core/ui/console.py", line 258, in start
    module.run()
  File "/home/viper/viper_testing/viper/viper/modules/emailparse.py", line 454, in run
    msg = parse_ole_msg(ole)
  File "/home/viper/viper_testing/viper/viper/modules/emailparse.py", line 63, in parse_ole_msg
    email_header = email_header.replace('\x00', '')
TypeError: a bytes-like object is required, not 'str'
```

stream[0] is: `__substg1.0_007D001F` and email_header: `b'R\x00e\x00c\x00e\x0[...]\r\x00\n\x00'`

**Comment by Rafiot** [comment]
I'll work on it asap. the TODO is to open the file as bytes and decode if needed.

**Comment by frennkie** [comment]
I  started but got stuck.. the first fix is to handle this line differently on Py2 and Py3: https://github.com/viper-framework/viper/blob/master/viper/modules/emailparse.py#L58. Doing `email_header = email_header.decode('utf-8')`on Py3 seems to give me a readable header.. but still `msg = email.message_from_string(email_header)` (L70) produces an object that doesn't not seem to have a valid data in the headers. :-/
