### ISSUE TITLE
csrf token failure - reports.py using cookies.py fails

### ISSUE THREAD

**Issue by Melwer** [viper-framework/viper#577]
Hello dear friends,

i've been trying find answer for that all around without any success.

When i try the reports model it fails just after the username&password input - 

> Traceback (most recent call last):
  File "/opt/viper-1.2/viper/core/ui/console.py", line 253, in start
    module.run()
  File "/opt/viper-1.2/modules/reports.py", line 221, in run
    self.malwr()
  File "/opt/viper-1.2/modules/reports.py", line 88, in malwr
    csrf = sess.cookies['csrftoken']
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 276, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python2.7/dist-packages/requests/cookies.py", line 331, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

*Just for the record, i haven’t change a thing in the original git.

**Comment by frennkie** [comment]
@Melwer Could you please double check which version of Viper you are using? The recommendation is to use the latest Git version which is currently labeled as 1.3-dev (in viper-cli run `about`).

Additionally the recommended Python version for running Viper recently changed to Python3 (Python 2.7 should still work but some things (e.g. non Ascii characters in file names) are only supported with Python3+).

**Comment by frennkie** [comment]
I can confirm this.. I think the problem is that in the reports module in the malwr part the authentication is done with username + password. Malwr now provides an API key which should make it a lot simpler.

**Comment by botherder** [comment]
Yes, that's correct.
