### ISSUE TITLE
TypeError in PE module compiletime function

### ISSUE THREAD

**Issue by botherder** [viper-framework/viper#598]
Something changed in the PE module, as now the `pe compiletime --scan` option is not working properly.

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/core/ui/console.py", line 318, in start
    module.run()
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/modules/pe.py", line 1010, in run
    self.compiletime()
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/modules/pe.py", line 293, in compiletime
    delta = (compile_time - cur_compile_time)
TypeError: unsupported operand type(s) for -: 'str' and 'str'```

**Comment by frennkie** [comment]
Just tried to reproduce this but `pe compiletime --scan` works for me on both Python2&3.

Which version of pefile do you have? I have `pefile==2017.5.26`
