### ISSUE TITLE
r2 command - AttributeError: 'NoneType' object has no attribute 'command'

### ISSUE THREAD

**Issue by SnowI5Me** [viper-framework/viper#609]
Hello.

an error occurred while running the r2 command .

SPEC
    Ubuntu 16.04
     Python 3   

```
miss viper crackme0x01 > r2 --help
usage: r2 [-h] [command [command ...]]

Start Radare2

positional arguments:
  command     Run a radare2 command on the current file

optional arguments:
  -h, --help  show this help message and exit

[!] The command r2 raised an exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/core/ui/console.py", line 319, in start
    module.run()
  File "/usr/local/lib/python3.5/dist-packages/viper-1.3.dev0-py3.5.egg/viper/modules/radare.py", line 35, in run
    r2command = ' '.join(self.args.command)
AttributeError: 'NoneType' object has no attribute 'command'

```

Thanks in advance for your help.

**Comment by frennkie** [comment]
@Rafiot you can close this one (same as #620).

**Comment by Rafiot** [comment]
Good point, thanks :)
