### ISSUE TITLE
Unhandled exception on reports command

### ISSUE THREAD

**Issue by krmaxwell** [viper-framework/viper#61]
```
misc shell 9fc0fd8725f6cc85ac5ccca266d5130c > reports malwr
You need to specify a valid username/password, login now? [y/N] y
Username: krmaxwell
Password: 
[!] The command reports raised an exception:
Traceback (most recent call last):
  File "/mnt/viper/viper/core/ui/console.py", line 176, in start
    module.run()
  File "/mnt/viper/modules/reports.py", line 181, in run
    self.malwr()
  File "/mnt/viper/modules/reports.py", line 97, in malwr
    verify=False
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 425, in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 387, in send
    raise Timeout(e)
Timeout: HTTPSConnectionPool(host='malwr.com', port=443): Read timed out.
```

**Comment by deralexxx** [comment]
I am unable to verify it...

**Comment by kevthehermit** [comment]
Fixed with https://github.com/viper-framework/viper/pull/348/
