### ISSUE TITLE
Something wrong happened while importing the module viper.modules.emailparse: No module named olefile

### ISSUE THREAD

**Issue by IrootGeek** [viper-framework/viper#613]
Hi,
I execute viper-cli, but i get this error:
$ viper-cli
`[!] Something wrong happened while importing the module viper.modules.emailparse: No module named olefile
Traceback (most recent call last):
  File "/usr/local/bin/viper-cli", line 4, in <module>
    __import__('pkg_resources').run_script('viper==1.3.dev0', 'viper-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/EGG-INFO/scripts/viper-cli", line 8, in <module>
    from viper.core.ui import console
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/core/ui/console.py", line 19, in <module>
    from viper.core.plugins import __modules__
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/core/plugins.py", line 47, in <module>
    __modules__ = load_modules()
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/core/plugins.py", line 41, in load_modules
    parser_args=get_argparse_parser_actions(member_object().parser),
  File "/usr/local/lib/python2.7/dist-packages/viper-1.3.dev0-py2.7.egg/viper/modules/misp.py", line 175, in __init__
    temp_me = MISPEvent()
NameError: global name 'MISPEvent' is not defined
`

**Comment by Rafiot** [comment]
Did you install the dependencies? 

Something like that should do:
```
pip install -r requirements-modules.txt
```

**Comment by IrootGeek** [comment]
Hello,
Yes i did this, i solved this problem by manually installing python dependent packages.
Thank you
