### ISSUE TITLE
Can't run viper-cli

### ISSUE THREAD

**Issue by alex-bender** [viper-framework/viper#639]
Fresh version of viper (git clone) results in error during launch:
```
[!] Something wrong happened while importing the module viper.modules.emailparse: No module named 'olefile'
[!] Something wrong happened while importing the module viper.modules.joesandbox: No module named 'jbxapi'
Traceback (most recent call last):
  File "/usr/local/bin/viper-cli", line 4, in <module>
    __import__('pkg_resources').run_script('viper==1.3.dev0', 'viper-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/viper-1.3.dev0-py3.6.egg/EGG-INFO/scripts/viper-cli", line 8, in <module>
    from viper.core.ui import console
  File "/usr/local/lib/python3.6/dist-packages/viper-1.3.dev0-py3.6.egg/viper/core/ui/console.py", line 19, in <module>
    from viper.core.plugins import __modules__
  File "/usr/local/lib/python3.6/dist-packages/viper-1.3.dev0-py3.6.egg/viper/core/plugins.py", line 47, in <module>
    __modules__ = load_modules()
  File "/usr/local/lib/python3.6/dist-packages/viper-1.3.dev0-py3.6.egg/viper/core/plugins.py", line 41, in load_modules
    parser_args=get_argparse_parser_actions(member_object().parser),
  File "/usr/local/lib/python3.6/dist-packages/viper-1.3.dev0-py3.6.egg/viper/modules/misp.py", line 170, in __init__
    temp_me = MISPEvent()
NameError: name 'MISPEvent' is not defined
```
OS: Debian 8
Python: 3.6

`pip3 install pymisp`
resolves this issue

**Comment by Rafiot** [comment]
Woops, good point, I'm fixing it, thanks

**Comment by alex-bender** [comment]
Whoa! Super fast response -- Thanks!
