### ISSUE TITLE
Issue running viper-web

### ISSUE THREAD

**Issue by mattulm** [viper-framework/viper#666]
./viper-web
Traceback (most recent call last):
  File "./viper-web", line 22, in <module>
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'favicon'

Where can i find this module, please?

**Comment by frennkie** [comment]
Hm.. django-favicon is listed in `requirements-web.txt`. Can you run this and check whether that fixes it:

```
pip install -r requirements-web.txt
```

**Comment by mattulm** [comment]
This did not work for me.
I went back and followed the other link to the docs I was given, and it worked. Still got a few errors, but upgraded Django and it works for me so far. A few Modules don't but I'm sure those can be fixed.
