### ISSUE TITLE
Joe Sandbox -> unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by ITSEC-DACHSER** [viper-framework/viper#749]
Seems there is an error in the Joe Sandbox Module since the last commit --> https://github.com/viper-framework/viper/commit/39c4791e906b8a61686dfab11cd6df21b2b2c7ef

**Here is the output:**

```
/usr/local/src/viper$ /usr/local/src/viper/viper-cli -p IT-SEC
You have 34 files in your IT-SEC repository
IT-SEC viper > joe
[!] The command joe raised an exception:
Traceback (most recent call last):
  File "/usr/local/src/viper/viper/core/ui/console.py", line 313, in start
    module.run()
  File "/usr/local/src/viper/viper/modules/joesandbox.py", line 52, in run
    user_agent="viper")
TypeError: __init__() got an unexpected keyword argument 'user_agent'
IT-SEC viper > exit

```

**Comment by ITSEC-DACHSER** [comment]
Got it. 
Used still old Python API Module, sorry.
