### ISSUE TITLE
libyara.so undefined symbol: Lookup rule

### ISSUE THREAD

**Issue by delbs27** [viper-framework/viper#761]
Hi, installed the latest version of viper on ubuntu 18.04 as per the first-launch doco https://viper-framework.readthedocs.io/en/latest/installation/index.html#first-launch. 

Install proceeded without any errors reported. 

first launch of viper-cli results in the below error 

viper-cli 
Traceback (most recent call last):
  File "./viper-cli", line 10, in <module>
    from viper.core.ui import console
  File "/home/delbs/viper/viper/core/ui/console.py", line 19, in <module>
    from viper.core.plugins import __modules__
  File "/home/delbs/viper/viper/core/plugins.py", line 81, in <module>
    __modules__ = load_modules()
  File "/home/delbs/viper/viper/core/plugins.py", line 62, in load_modules
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/delbs/viper/viper/modules/rat.py", line 19, in <module>
    import yara
  File "/usr/local/lib/python3.6/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python3.6/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python3.6/dist-packages/yara/libyara_wrapper.py", line 362, in <module>
    libyaradll.lookup_rule.restype = POINTER(RULE)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule

yara and yara-python modules are installed, yara from source and yara-python from pip. 

Has anyone else come across this error and what i could be missing for this to error  to occur? 

Thanks in advance

**Comment by delbs27** [comment]
Cancel this, installed under a clean venv and it works fine, i think i have an issue with yara globally installed so a clean venv_viper fixed this.
